# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: SecureStack Application Composition Analysis
      # You may pin to the exact commit or the version.
      # uses: SecureStackCo/actions-code@c2c35840882d041474c505c1045da157025cd57e
      uses: SecureStackCo/actions-code@v0.1.1
      with:
        # SecureStack API key - generate an API key at https://app.securestack.com
        securestack_api_key: a70b7d82-216b-424f-8831-53920c9226ae.RwEO9Z6vRZjmoP9z64xx
        # SecureStack Application ID - can be retrieved by accessing required application at https://app.securestack.com
        securestack_app_id: bloodhound-cli init -k a70b7d82-216b-424f-8831-53920c9226ae.xZ9wMcbKGnpk7rMFzO3n
        # Severities lower than this value will be reported in the workflow console but will not cause an error for the action; value should be one of: critical | high | medium | low
        severity: medium
        # Severities lower than this value will be reported in the workflow console but will not cause an error for the action; value should be one of: critical | high | medium | low
        language: medium
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
