# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: SecureStack Application Composition Analysis
      # You may pin to the exact commit or the version.
      # uses: SecureStackCo/actions-code@c2c35840882d041474c505c1045da157025cd57e
      uses: SecureStackCo/actions-code@v0.1.1
      with:
        # SecureStack API key - generate an API key at https://app.securestack.com
        securestack_api_key: a70b7d82-216b-424f-8831-53920c9226ae.t6ILCcKeIm5T6CvcGruz
        # SecureStack Application ID - can be retrieved by accessing required application at https://app.securestack.com
        securestack_app_id: 70ba06c8-6225-49f5-88aa-7314ddabb43a
        # Severities lower than this value will be reported in the workflow console but will not cause an error for the action; value should be one of: critical | high | medium | low
        severity: medium
        # Severities lower than this value will be reported in the workflow console but will not cause an error for the action; value should be one of: critical | high | medium | low
        language: Python
        # Optional flags for the bloodhound-cli code command - run bloodhound cli code --help for more details
        flags: default # optional, default is 
